name: PostMaster
version: 1.0.3
main: io.nightbeam.postmaster.PostMasterPlugin
api-version: '1.20'
folia-supported: true
authors: [NightBeam]
description: Lightweight mailbox plugin for online and offline players.

commands:
  mail:
    description: Open mailbox and manage mail.
    usage: /mail
    aliases: [postmaster]
  mailbox:
    description: Open mailbox GUI.
    usage: /mailbox

permissions:
  postmaster.use:
    default: true
  postmaster.senditem:
    default: true
  postmaster.admin:
    default: op
